apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  labels:
    app: my-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem

  