apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  # type: LoadBalancer caso eu abra a internet
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    